---
title: "Pension Systems in North America Dashboard"
author: "Fernando Agustin Falbo"
date: "Jul 2020"
output:
  github_document:
  toc: true
---
  
The [Pension Systems in North America Dashboard](https://bit.ly/BDEFAFPSDASH) allows users to visualize information and different metrics based on data from pension systems in United States and Canada.

It is part of a research project at New York University. The complete dataset is available at [NYU libraries](http://scrc.scrc.nyu.edu/scrc/?page_id=3997) and comprises eleven years of historical data (2008 through 2018) for the 25 largest U.S. public pension plans and the ten largest Canadian public pension plans. The Canada dataset includes Canada Pension Plan and excludes pension plans in the province of Quebec. The U.S. dataset was used in Clive Lipshitz and Ingo Walter, "Bridging Public Pension Funds and Infrastructure Investing" (2019). The U.S. and Canada datasets were used in Lipshitz and Walter, "Public Pension Reform and the 49th Parallel: Lessons from Canada for the U.S." (2020). Almost all data was sourced from annual reports of the pension plans. Data includes: (1) Net pension liability (Liabilities, Funded status), (2) Discount rate, (3) Fiduciary net position (Plan assets – detailed by type), (4) Changes in financial position (Contributions, Benefits, Investment income – each detailed by type); (5) Contributions  (Employers, Plan members, rates), (6) Investment expenses (Investing, Administrative – by type), (7) Asset allocation, Actual – by asset class, (8) Asset allocation, Target – by asset class, (9) Investment performance – total, by asset class, (10) Macroeconomic data (Inflation assumptions), (11) Pension plan demographics (active, annuitant, deferred members). In aggregate the dataset comprises 15,487 observations including 6,425 in the Canada dataset and 9,062 in the U.S. dataset (additional data, not in this dataset, was used in the two papers noted above). The dataset was developed in stages between January 2018 and June 2020, primarily by Fernando Falbo, as well as by Patricio Cox and Lebogang Mahlare, under the guidance of Lipshitz and Walter. 


